Add global $  generated amount
Glo-Foundation/glo-wallet pull request #455
Opened 2024-11-22 17:59 UTC by gabrieltemtsen

Database: Added FundingChoicesCache to store possibleFundingChoices.

Endpoint: Created /api/funding/updateCache to fetch and update the cache then created /api/funding/getChoices to get the possible funding choices from the DB.

Cron Job: Configured a daily cron job in vercel.json to auto-update the cache.
__
Add CRON_SECRET to .env.
Deploy and the cron job should trigger automatically.

2024-12-03 11:05 UTC, gabrieltemtsen commented
resolved conflicts @gglucass

2024-12-04 09:59 UTC, Riglanto requested changes
Looks quite good with the cron idea.

However I'd simplify the whole process to:
1. The cron should execute the code that's currently under `/api/funding/current` and store it in the db.
2. The `/api/funding/current` should just fetch the latest record from db.
3. The recipients endpoint can fetch data from `/api/funding/current`

In the end code will be way simpler, less endpoints and easier to maintain :)

2024-12-04 09:59 UTC, Riglanto commented on prisma/migrations/20241121122552_add_funding_choices_cache/migration.sql
> +DROP TABLE "CachedFundingChoice";
This will break as table does not exist.

2024-12-04 09:59 UTC, Riglanto commented on components/Recipients.tsx
> +  console.log(fundingChoices);
Remove console.log

2024-12-04 09:59 UTC, Riglanto commented on components/Recipients.tsx
> +  useEffect(() => {
Perhaps a good opportunity to useSWR (https://swr.vercel.app/) - optional comment.

2024-12-04 09:59 UTC, Riglanto commented on components/Recipients.tsx
> +            of the <b> ${totalYield.toFixed(2) || 0}/year </b>
I'd hide this part if `totalYield` is not avaialable.

2024-12-04 09:59 UTC, Riglanto commented on prisma/schema.prisma
> +  updatedAt DateTime  @default(now()) @updatedAt
=> `createdAt` as the entity is not going to be updated.

2024-12-04 09:59 UTC, Riglanto commented on pages/api/funding/updateCache.ts
> +      "https://app.glodollar.org/api/funding/current"
Always use relative path `/api/funding/current`

2024-12-09 09:28 UTC, gabrieltemtsen commented on components/Recipients.tsx
> +  console.log(fundingChoices);
alright

2024-12-09 11:33 UTC, gabrieltemtsen commented
@Riglanto I've made the requested changes

cc @gglucass

2025-01-06 09:44 UTC, merged

2025-01-06 09:44 UTC, gglucass commented
Thanks a lot for this @gabrieltemtsen - apologies that it took some time to merge due to EOY rush and holidays.

2025-01-06 09:57 UTC, gabrieltemtsen commented
Thank you!, unto the next issues now